---
- name: Update Upgrade & Clean APT Linux
  hosts: all
  vars:
    ansible_ssh_port: 3891
    
  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
        clean: yes
